[package]
name = "compose"
version = "0.1.0"
edition = "2024"

[dependencies]
url = "2.5"
anyhow = "1.0"
regex = "1.10"
directories = "5.0"
nix = { version = "0.27", features = ["user"] }
clap = { version = "4.4", features = ["derive"] }

[profile.release]
opt-level = "z"
strip = true
lto = true
codegen-units = 1
panic = "abort"
