#!/bin/bash
set -e

# Detect directories
XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
XDG_DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"
BIN_DIR="$HOME/.local/bin"
SYSTEMD_DIR="$XDG_CONFIG_HOME/systemd/user"
CONFIG_DIR="$XDG_CONFIG_HOME/docker"
CONF_FILE="$CONFIG_DIR/compose.env"

# Required keys for validation
REQUIRED_KEYS=(
    "COMPOSE_DATA"
    "COMPOSE_BASE"
    "TRAEFIK_ACME_DOMAIN"
    "TRAEFIK_ACME_EMAIL"
    "TRAEFIK_ACME_SERVER"
    "DOCKER_HOST"
    "DOCKER_SOCK"
)

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

log_info() { echo -e "${BLUE}>>${NC} $1"; }
log_success() { echo -e "${GREEN}OK${NC} $1"; }
log_warn() { echo -e "${YELLOW}WARN${NC} $1"; }
log_err() { echo -e "${RED}ERR${NC} $1"; }

# Function to validate an env file contains all required keys
validate_env_file() {
    local file=$1
    local missing=0
    
    if [ ! -f "$file" ]; then
        log_err "File not found: $file"
        return 1
    fi

    for key in "${REQUIRED_KEYS[@]}"; do
        if ! grep -q "^[[:space:]]*$key=" "$file"; then
            log_err "Missing required key: $key"
            missing=1
        fi
    done

    if [ $missing -eq 1 ]; then
        return 1
    fi
    return 0
}

# Function for interactive configuration
interactive_setup() {
    local temp_file=$(mktemp) 
    
    # Determine defaults based on current user
    local default_data="/srv/data"
    local default_base="/srv/compose"
    local default_docker_sock="/var/run/docker.sock"
    
    if [ "$EUID" -ne 0 ]; then
        default_data="$HOME/data"
        default_base="$HOME/compose-projects"
        default_docker_sock="/run/user/$(id -u)/docker.sock"
    fi

    echo -e "\n${YELLOW}Interactive Configuration:${NC}"
    echo "Press Enter to accept the default values."
    
    read -p "COMPOSE_DATA [$default_data]: " val_data
    val_data=${val_data:-$default_data}
    
    read -p "COMPOSE_BASE [$default_base]: " val_base
    val_base=${val_base:-$default_base}
    
    read -p "TRAEFIK_ACME_DOMAIN [example.com]: " val_domain
    val_domain=${val_domain:-example.com}
    
    read -p "TRAEFIK_ACME_EMAIL [admin@example.com]: " val_email
    val_email=${val_email:-admin@example.com}
    
    read -p "TRAEFIK_ACME_SERVER [https://acme-v02.api.letsencrypt.org/directory]: " val_server
    val_server=${val_server:-https://acme-v02.api.letsencrypt.org/directory}
    
    read -p "DOCKER_SOCK [$default_docker_sock]: " val_sock
    val_sock=${val_sock:-$default_docker_sock}
    
    local default_host="unix://$val_sock"
    read -p "DOCKER_HOST [$default_host]: " val_host
    val_host=${val_host:-$default_host}

    # Write to temp file
    cat > "$temp_file" <<EOF
# Generated by install.sh on $(date)
COMPOSE_DATA=$val_data
COMPOSE_BASE=$val_base

TRAEFIK_ACME_DOMAIN=$val_domain
TRAEFIK_ACME_EMAIL=$val_email
TRAEFIK_ACME_SERVER=$val_server

DOCKER_HOST=$val_host
DOCKER_SOCK=$val_sock
EOF

    # Install the file
    mkdir -p "$CONFIG_DIR"
    cp "$temp_file" "$CONF_FILE"
    rm "$temp_file"
    log_success "Configuration written to $CONF_FILE"
}

# Parse Arguments
INPUT_ENV=""
while [[ $# -gt 0 ]]; do
    case $1 in
        --env-file)
            INPUT_ENV="$2"
            shift 2
            ;; 
        *)
            echo "Unknown option: $1"
            exit 1
            ;; 
    esac
done

# Main Installation Flow
log_info "Starting installation..."

# 1. Build Binary
log_info "Building release binary..."
cargo build --release --quiet

# 2. Install Binary
log_info "Installing binary to $BIN_DIR..."
mkdir -p "$BIN_DIR"
install -Dm755 "target/release/compose" "$BIN_DIR/compose"

# 3. Install Systemd Unit
log_info "Installing systemd unit to $SYSTEMD_DIR..."
mkdir -p "$SYSTEMD_DIR"
install -Dm644 "systemd/compose@.service" "$SYSTEMD_DIR/compose@.service"
# Replace placeholder with actual binary path
sed -i "s|BINARY_PATH|$BIN_DIR/compose|g" "$SYSTEMD_DIR/compose@.service"

# 4. Handle Configuration
mkdir -p "$CONFIG_DIR"

if [ -n "$INPUT_ENV" ]; then
    log_info "Validating provided env file: $INPUT_ENV"
    if validate_env_file "$INPUT_ENV"; then
        cp "$INPUT_ENV" "$CONF_FILE"
        log_success "Configuration installed from $INPUT_ENV"
    else
        log_err "Validation failed. Aborting."
        exit 1
    fi
else
    if [ -f "$CONF_FILE" ]; then
        echo -e "\nConfiguration file already exists at: $CONF_FILE"
        read -p "Do you want to reconfigure it? [y/N] " choice
        case "$choice" in 
            y|Y ) RECONFIGURE=1 ;; 
            * ) RECONFIGURE=0 ;; 
        esac
    else
        RECONFIGURE=1
    fi

    if [ "$RECONFIGURE" -eq 1 ]; then
        echo -e "\nHow do you want to configure?"
        echo "1) Interactive Setup (Guided)"
        echo "2) Manual Edit (Creates file and exits info)"
        read -p "Select [1-2]: " mode

        case "$mode" in
            2)
                # Manual
                if [ ! -f "$CONF_FILE" ]; then
                    cp "systemd/compose.env" "$CONF_FILE"
                    
                    # Try to adjust defaults even for manual start
                    if [ "$EUID" -ne 0 ]; then
                        sed -i "s|/srv/data|$HOME/data|g" "$CONF_FILE"
                        sed -i "s|/srv/compose|$HOME/compose-projects|g" "$CONF_FILE"
                        sed -i "s|/var/run/docker.sock|/run/user/$(id -u)/docker.sock|g" "$CONF_FILE"
                    fi
                fi
                log_warn "Manual mode selected."
                echo "Please edit the configuration file at:"
                echo "  $CONF_FILE"
                echo "Ensure all required variables are set."
                ;; 
            *)
                # Interactive (Default)
                interactive_setup
                ;; 
        esac
    else
        log_info "Skipping configuration update."
    fi
fi

# 5. Reload Systemd
log_info "Reloading systemd --user..."
systemctl --user daemon-reload

echo ""
log_success "Installation Complete!"
echo "   - Binary:  $BIN_DIR/compose"
echo "   - Config:  $CONF_FILE"
echo "   - Service: $SYSTEMD_DIR/compose@.service"

echo ""
echo "   Make sure $BIN_DIR is in your PATH."
